FROM python:3.8-buster

RUN apt-get update
RUN apt-get install -y fonts-ipafont
RUN pip install --upgrade pip
RUN pip install python-dotenv
RUN pip install numpy
RUN pip install mysqlclient
RUN pip install matplotlib
RUN pip install seaborn
RUN pip install requests
# https://analytics-note.xyz/aws/ec2-ipafont/